### ISSUE TITLE
Multichannel .tiff plus add an ome.xml header

### ISSUE THREAD

**Issue by rmassei** [gitdemont/IFC#5]
Hi @gitdemont,
first of all thanks for this great work. I recently start to use IFC for extracting flow citometry images from .cif and it works great.

I recently open a topic in the image.sc forum regarding the data management of flow citometry data (https://forum.image.sc/t/data-management-workflow-for-flow-cytometry-data/91882). The package IFC helped me greatly, but I was wondering if it is also possible to:
- [x] Within R, extract a multichannel image and not only single channels from the .cif file (done with `IFC` package `version >= 0.2.1.600`)
- [x] Add an ome.xml header to the .tiff file in order to embed directly the metadata to the image header (done with  `IFC` package `version == 0.2.1.611`)
- [x] Alternatively, recreate the multichannel image outside R (edited to keep initial task numbers)

At the moment I am using a python script to perform these two steps (https://github.com/rmassei/IFC/blob/dev_python/python/multichannel_conversion_ome.py). The xml header is based on the study of Dunker et al. (2021) (doi: 10.1111/nph.16882).

**Comment by gitdemont** [comment]
Hi @rmassei ,
Thanks !

You already manage to perform those steps outside with a python script so what would you expect / need ?
There are several considerations I can see (please add to the list):
- having a all-in-one-pot solution (all is performed in R). However, will this still be true for your full workflow ? Wouldn't you need to go to python afterward ?
- having a very fast solution. However, in your workflow does this step represent a huge bottleneck ? Besides, I am not sure that there could be someting faster than what you already do ( although there are for sure some overhead with exporting to mono channels files and then reading them so as to create another multichannel file, meaning writting to HDD twice )
- having a nice format for managing data. I see that there is a [demand for multichannel tiff ](https://github.com/gitdemont/IFC/issues/3#issuecomment-1878815581). However, as with the script you are using, users may already take advantage of what `IFC` package could return to produce further custom outputs.

That being said, I did some testings to further delineate this issue and hopefully help.

---
[`tiff`](https://github.com/s-u/tiff) package, which is used in `IFC` can not export multichannel tiff files (only gray, or RGB/A)
[`ijtiff`](https://github.com/ropensci/ijtiff) and [`RBioFormats`](https://github.com/aoles/RBioFormats), however, seems to be good candidates.

So, I tried to create multichannel tiff files with those packages:
```R
# create temp file to store image and create multichannel image with random values [-30,4095], including negative ones
set.seed(1)
f = tempfile(fileext = ".tif")
IMGs = lapply(1:5, FUN = function(x) matrix(sample(-30:4095L, size = 75 * 86, replace = T), ncol = 86))
IMGs = abind::abind(abind::abind(IMGs, along = 3), along = 4)
str(IMGs) # int [1:75, 1:86, 1:5, 1] 75 rows, 86 cols, 5 channels, 1 frame

# write/read multichannel image with ijtiff package
ijtiff::tif_write(img = IMGs, path = f, overwrite = TRUE, bits_per_sample = 16L) # not working due to negative values
ijtiff::tif_write(img = IMGs, path = f, overwrite = TRUE)                        # works but store IMGs as float
V = ijtiff::tif_read(f)
all(V == IMGs) # TRUE

# write/read multichannel image with RBioFormats package
RBioFormats::write.image(x = IMGs, file = f, force = TRUE, pixelType = "int16")
V = RBioFormats::read.image(f, normalize = FALSE)
all(V == IMGs[,,,1]) # FALSE, I think this is not expected, I will submit an issue to get light from package maintainer
```
To me, it shows that 1st task is feasible within R.
As `IFC` is conceived it wouldn't be a direct cif export multichannel file ([as it is done for single channel file](https://github.com/gitdemont/IFC/blob/0cabbda1694938aa233d887145dead59216e1a97/R/objectExtract.R#L204)) but rather a batch extraction of images to matrix followed by file export to multichannel tiff which I believe could still be fast.

---
Now, for the 2nd task, (please consider that I may not have tested things thouroughly enough), I see no direct solution for incorporating custom ome-xml:
- in `ijtiff`, there seems to be an open issue that could link to what you need, https://github.com/ropensci/ijtiff/issues/18
- in `RBioFormats`, which, if I understand well, is theoriticaly particularly designed for what you need (interface to the OME Bio-Format), it seems that is not yet possible to modify ome-xml, https://github.com/aoles/RBioFormats/issues/40
- create a custom function to edit/add custm ome-xml. I have no experience with OME-TIFF standard

```r
# lets look at a sample file of OME-TIFF
ome_tiff = tempfile(fileext = ".tif")
curl::curl_download(url = "https://downloads.openmicroscopy.org/images/OME-TIFF/2016-06/bioformats-artificial/multi-channel.ome.tif", destfile = ome_tiff)

# with IFC package we can inspect tiff TAGS from IFD (Image Field Directory) within the file
# lets look at 1st IFD containg 1st image (here 1st channel)
IFD1 = IFC::getIFD(ome_tiff, "first")
sapply(IFD1[[1]]$tags, FUN = function(x) x)
IFC::getFullTag(IFD = IFD1, which = 1, tag = "270") # looks like ome.xml is written here

# lets look at the other IFDs containing image 2 and 3 (here channels 2 and 3)
IFDs = IFC::getIFD(ome_tiff, "all")
sapply(IFDs[[1]]$tags, FUN = function(x) x)
IFC::getFullTag(IFD = IFDs, which = 1, tag = "270") # general info about the structure of the file
# "ImageJ=\nhyperstack=true\nimages=3\nchannels=3\nslices=1\nframes=1"
```
Looks like tag 270 in the 1st IFD is the place to register the ome-xml metadata

**Comment by rmassei** [comment]
Hi @gitdemont,
thank for your comprehensive reply.

> having a all-in-one-pot solution (all is performed in R). However, will this still be true for your full workflow ? Wouldn't you need to go to python afterward ?

I guess this would be a nice option since there will be the possibility to run everything in R without the need of jumping to python in the middle of the pipeline. 

> having a very fast solution. However, in your workflow does this step represent a huge bottleneck ? Besides, I am not sure that there could be someting faster than what you already do ( although there are for sure some overhead with exporting to mono channels files and then reading them so as to create another multichannel file, meaning writting to HDD twice )

A fast an easy solution would be to run everything in a JN using the package [rpy2](https://rpy2.github.io/).
```
path_to_R = "path to R"
os.environ['R_HOME'] = f"{path_to_R}"
from rpy2.robjects.packages import IFC
#Run the IFC script
```
This should work but I do not know the drawbacks to run IFC with such approach and the limitations of JN when working with huge datasets. But for sure this can already be tested and applied

> having a nice format for managing data. I see that there is a https://github.com/gitdemont/IFC/issues/3#issuecomment-1878815581. However, as with the script you are using, users may already take advantage of what IFC package could return to produce further custom outputs.

True, and this can be probably achieved within R with your script using [ijtiff](https://github.com/ropensci/ijtiff) and [RBioFormats](https://github.com/aoles/RBioFormats), correct?

Regarding the 2nd task:
yes, tag 270 is the correct one since it is the [image description tag](https://www.awaresystems.be/imaging/tiff/tifftags/imagedescription.html).
A nice approach would be to get metadata from the .cif file using getInfo, build the ome.xml using these info (i.e. some aquisition info such as $illumination) and then inject them in the .tiff description.

**Comment by gitdemont** [comment]
Hi @rmassei ,

I will be engaged in several projects. So please, don't expect replies from myself within the next 3 weeks.
In addition, I think it's important to wait for answers from `ijtiff` and `RBioFormat`.
Besides, I also started things independetly from those packages. But I nonetheless need to wait to pick-up best decision.

PS:
-For JN, I don't know too. Hope it should work without any problems (except maybe for some visualizations functions involving HTML)
-In addition, to rpy2, you may also consider [`reticulate`](https://github.com/rstudio/reticulate)
-Yes, it looks like it will be possible to perform everything within `R` (at least exporting multichannel tiff is possible, it remains to see how to correctly integrate xml metadata). Then, this `R` solution will need to be tested and compared with your `python` script in term of speed, ease-to-use, accuracy ...

**Comment by aoles** [comment]
Hi @gitdemont 

thanks for your interest in using [RBioFormats](https://github.com/aoles/RBioFormats). There has been indeed a bug in the `write.image` function which I've just fixed. As a new BioC release is scheduled only in two weeks time, the fix will be soon available in RBioFormats v1.4. You can, however, already test in on GitHub, see below.

Regarding the metadata part, could you maybe give me a concrete example of what you would like to achieve such that I get a better understanding of the problem and requirements?

Cheers!
Andrzej

``` r
# remotes::install_github("aoles/RBioFormats")

# create temp file to store image and create multichannel image with random values [-30,4095]
set.seed(1)
f = tempfile(fileext = ".tif")
IMGs = lapply(1:5, FUN = function(x) matrix(sample(-30:4095L, size = 75 * 86, replace = T), ncol = 86))
IMGs = abind::abind(abind::abind(IMGs, along = 3), along = 4)
str(IMGs)
#>  int [1:75, 1:86, 1:5, 1] 986 2146 1502 2316 239 4019 3348 4034 566 1270 ...
#>  - attr(*, "dimnames")=List of 4
#>   ..$ : NULL
#>   ..$ : NULL
#>   ..$ : NULL
#>   ..$ : NULL

RBioFormats::write.image(x = IMGs, file = f, force = TRUE, pixelType = "int16")
V = RBioFormats::read.image(f, normalize = FALSE)
all(V == IMGs[,,,1])
#> [1] TRUE
```

<sup>Created on 2024-04-17 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by gitdemont** [comment]
Thanks @aoles for the fix

For the metadata, the idea is to place string (more precisely xml) in tag **270** to embed [image description ](https://github.com/rmassei/IFC/blob/dev_python/python/multichannel_conversion_ome.py) 1st comment o the present issue.
Pinging @rmassei to further describe what he wants.

Although I mentioned [issue with editing](https://github.com/aoles/RBioFormats/issues/40) already existing **270** tag, from my perspective, I think it would be nice to fill this tag at file creation time e.g. with additionnal argument in **write.tiff** function `metadata` that user could use to input a string like `"<xml version=1.0 encoding="UTF8"><OME></OME>"`

Note that ability to edit already existing **270** (or arbitrary one) tag is also something highly desirable _per se_

**Comment by rmassei** [comment]
Hi @aoles 
the goal is to  add an OME-XML metadata block in each TIFF tag270. The goal is to embed additional metadata to the tiff in a standardize format and can be read by Bio-formats. As example, the IFC package can extract channels' metadata in a tabular form which would be nice to add directly to the image.
At the present, I am managing to doing it using python by 1) building the ome.xml using [ome-types](https://github.com/tlambert03/ome-types) and 2) adding it in the description with [tifffile](https://github.com/cgohlke/tifffile). I am wondering if everything might be achieve in the R environment.

**Comment by rmassei** [comment]
As a additional info and update, I created a repository with the complete workflow:
https://github.com/rmassei/2024_flowcitometry_multichannel

**Comment by aoles** [comment]
Hi @rmassei,

thanks for providing the additional info. I will look into implementing such functionality into RBioFormats, so stay tuned.

Cheers,
Andrzej

**Comment by gitdemont** [comment]
Hi @rmassei ,

You should now be able to export multichannel tiff files with `IFC` package `version >= 0.2.1.600`
This new feature is totally integrated in the package workflow with new allowed value `"multi"` to `export` argument of objectParam.
New functions **ExtractImages_toMulti**, **ExtractMasks_toMulti** can be used to facilitate the workflow.

For the moment, this is highly experimental and it is based on new internal functions to write tiff.
Those new internal functions are created so that almost any arbitrary tags can be easily incorporated in exported files (and notably tag **270**). The main advantages I see is that it removes dependency and that it is specially dedicated for the current taks/issue. However, I still need to see if this works or to decide if it is preferable to rely on well established/maintained R packages.

Still, it remains the 2nd tasks of incorporating ome-xml, though.
As said, incorporating **270** tag should now be trivial with `IFC 0.2.1.600`. However, having valid ome-xml in this tag is not.
There are still some steps to complete and define how to fullfill ome-xml standard (I do not know the standard and help from expert is required):
o what are minimal information ? what are extra but nice information ?
o how should they be stored (which keyword, which type) ?
o then, find a mean to inject those in the workflow of image export (**objectParam** function may be the best place to pass values from extracted information obtained by **getInfo**)
o then, create a dedicated function to write xml from parameters to include in ome-xml

**Comment by rmassei** [comment]
Hi @gitdemont,
thanks a lot for this!
I can support with input on the schema. At the present, I am travelling and I will take care to give you a more comprehensive answer once I am back.

**Comment by rmassei** [comment]
Hi @gitdemont sorry for my late reply. Thanks a lot for this, it actually looks great!

Regarging the ome-xml: with **getInfo** it is possible to already get some additional metadata which can be added to the ome-xml (i.e. emission wavelength). In my opinion, the optimal steps would be 1) get the metadata from the .cif file using **getInfo**, 2) create an xml file containing these metadata following the ome-xml schema and 3) in **ExtractImages_toMulti** add an argument injecting the ome-xml in tag 270 of each multichannel image. While some information will be unique for each image (i.e. image name and uuid) all the other acquisition values would be the same. This follow more or less your steps, am I right?

The ome-xml format is quite large and complex but I would be happy to help with it.  If it can helps, I can share an example with you based on the IFC examples data.

**Comment by gitdemont** [comment]
Hi,

I am reluctant at adding a new argument to **Extract[Images/Masks]_toMulti** because if this will work with this function, it will not allow user to add ome-xml in downstream function **objectExtract**. And adding this argument to **objectExtract** would be higlhly inefficient

Basically, **objectExtract** uses **objectParam** to get all required `param` to extract/normalize/export images/masks from `ifd`.
So the best bet is certainly to add metadata needed for ome-xml as part of the returned value of **objectParam**.
However, this represents a MAJOR change (though it is addition and not removal)
Another option is to not modify returned value of **objectParam** and only use info it already contains.

This is the reason of my questions in previous comment:
`what are minimal information ? what are extra but nice information ?`
So I need to know what:
- should (mandatory) be in ome-xml that if not present will lead to error/warning/undesired behaviour when read afterwards
- could be in ome-xml that if present will provide usefull extra

Maybe **objectParam** already contains the mandatory values.
Maybe it's better not to overload every **`.tiff`** produced from a same **`.rif/.cif`** file with the same extra meta data but rather include a single **`.xml/.txt`** (or so) to the batch of extracted files

For my previous 2nd question:
`how should they be stored (which keyword, which type) ?`
 I need to know:
- for both (mandatory and extra) how they should be written in the xml-ome so they can be correctly parsed afterwards

Yes please include here some **`.tiff`** files produced from `IFCdata` example files (e.g. one from image, one from mask, both from **`.rif/.cif`**) that satisfy downstream ome workflow

**Comment by gitdemont** [comment]
Hi @rmassei ,

I have just commited `IFC` package `version = 0.2.1.604` which can be a solution that combines previously discussed points (multichannel tiff with metadata and all in R). To install it:
```r
unload(package = "IFC")
remove.packages("IFC")
remotes::install_github("gitdemont/IFC", ref = "3bf88e3b42e9ffa21d1fb358ca16e969e9929b5d")
```
With this version, TIFF files are exported with "N/A" in ImageDescription **270** tag.
Then this tag can be edited by user to inject its own metadata.
**editMetadata** a new **not exported function (only here to test things)** is designed to accomplish this task. 
So this let you the possibility to pass the information you need in the ome-xml you create as a simple string. As an example:
```r
cif_file = system.file(package = "IFCdata", "extdata", "example.cif")
d = tempdir()

# export images of objects 1,3 and 4 of cif_file to multichannel TIFF files
exported_file_list = IFC::ExtractImages_toMulti(fileName = cif_file, objects = c(1,3,4), write_to = file.path(d, "%s_%o.tiff"), force_width = FALSE, size = c(0,0), overwrite = T)

# will print "N/A" in tag 270
lapply(exported_file_list, FUN = function(f) {
  IFD = IFC::getIFD(f)
  print(sapply(IFD[[1]]$tags, FUN = function(x) x))
})

# edit metadata in exported_file_list files
modified_file_list = sapply(exported_file_list, FUN = function(f) {
  IFC:::editMetadata(f, metadata = "newmetadata")
})

# will print "newmetadata" in tag 270
lapply(exported_file_list, FUN = function(f) {
  IFD = IFC::getIFD(f)
  print(sapply(IFD[[1]]$tags, FUN = function(x) x))
})
``` 

PS: **editMetadata** is only present in `version = 0.2.1.604` and has been removed a time of writing this

**Comment by rmassei** [comment]
Hi @gitdemont,
sorry if I reply with some delay but I am also dealing with some other tasks.
I will run some tests with 0.2.1.604 and I will let you know. In the meanwhile to answer to some of your questions:

> This is the reason of my questions in previous comment: `what are minimal information ? what are extra but nice information ?` So I need to know what:
> 
>     * should (mandatory) be in ome-xml that if not present will lead to error/warning/undesired behaviour when read afterwards
> 
>    

there is an amount of [minimum information](https://ome-model.readthedocs.io/en/stable/specifications/minimum.html) for the ome-xml. The image will be unreadable if any of the required Pixel attributes are missing. I guess all these info are in **objectParam**.

>  * could be in ome-xml that if present will provide usefull extra
>
>  For my previous 2nd question: `how should they be stored (which keyword, which type) ?` I need to know:
> 
>     * for both (mandatory and extra) how they should be written in the xml-ome so they can be correctly parsed afterwards
> 
> 
> Yes please include here some **`.tiff`** files produced from `IFCdata` example files (e.g. one from image, one from mask, both from **`.rif/.cif`**) that satisfy downstream ome workflow

Here two example of multichannel tiff created from IFCdata, both .cif and .rif

[multichannel_output_2024-05-24 20:54:47_rif.tar.gz](https://github.com/gitdemont/IFC/files/15438904/multichannel_output_2024-05-24.20.54.47_rif.tar.gz)
[multichannel_output_2024-05-24 20:52:19_cif.tar.gz](https://github.com/gitdemont/IFC/files/15438905/multichannel_output_2024-05-24.20.52.19_cif.tar.gz)

images were created using my python script.
I add an example of the ome.xml for an image in tag270. 
More information can be probably add in "Channels" according to the [xml schema](http://www.openmicroscopy.org/Schemas/Documentation/Generated/OME-2016-06/ome.html), such as EmissionWavelength, EmissionWavelengthUnit, ExcitationWavelength or ExcitationWavelengthUnit. 

I add in the folder also a json metadata file created starting from **getInfo**:

```
metadata <- getInfo(fileName = "file_name", from = "analysis")
metadata$illumination$Channel <- 1:nrow(metadata$illumination)
## extract metadata and save it as json file
wavelenght <- as.list(metadata$illumination$wavelength)
metadata_flat <- list(number_objects = metadata$objcount,
                      date = metadata$date,
                      instrument = metadata$instrument,
                      brightfield = metadata$brightfield,
                      illumination = metadata$illumination,
                      images = metadata$Images,
                      mask = metadata$masks,
                      wavelenght = wavelenght)
json_data <- toJSON(metadata_flat, pretty = TRUE)
write(json_data, file = "metadata.json")

```
This file contain information which I think can be defined "nice and extra" :) I will also check how these can be integrated in the xml.

**Comment by gitdemont** [comment]
Hi @rmassei ,

I have just commited `IFC` package `version = 0.2.1.611` where you will find necesseray tools to achieve (hopefully) your needs. To install it:
```r
unload(package = "IFC")
remove.packages("IFC")
remotes::install_github("gitdemont/IFC", ref = "7480440c506b5997187c3771e62afbb65e06cc0f")
```

With this version you can write multichannel **`.tiff`** file in an integrated and simple workflow using **Extract[Images/Masks]_toMulti** (which appeared in `0.2.1.600`)
And you can, in addition, edit tag[**270**] with your own text (which appeared in `0.2.1.604`)
And you can now use **createOME** to build ome-xml file directly in R that contains rich info.
I placed several *FIXME* so you can easily fork and customize parts (also wrote an example with 'instrument' to show you how you may add extra) https://github.com/gitdemont/IFC/blob/7480440c506b5997187c3771e62afbb65e06cc0f/R/ome.R#L155-L174

I think I will keep the ability to export multichannel tiff files.
However, I am not willing to integrate OME directly in the **`.tiff`** files at creation time because:
- many OME-XML info can be found in other **`.tiff`** tags.
- the one that are not (e.g. channel info) can be stored directly in tag[**270**] in different ways (base64, text, or so) or since they are highly redundant, they may be saved as companion extra file (**`.xml`**, **`.txt`**, **`.json`**, ...))
- **so**, I prefer to let the user choose.

```r
rif_file = system.file(package = "IFCdata", "extdata", "example.rif")
d = tempdir()
param = IFC::objectParam(fileName = rif_file, write_to = file.path(d, "%s_%o.tiff"), force_width = FALSE, size = c(0,0), overwrite = TRUE)

# export images of objects 1,156 and 419 of rif_file to export as multichannel tiff files
exported_file_list = IFC::ExtractImages_toMulti(param = param, objects = c(1,156,419), overwrite = TRUE)

# will print "N/A" in tag 270
lapply(exported_file_list, FUN = function(f) {
  IFD = IFC::getIFD(f)
  print(sapply(IFD[[1]]$tags, FUN = function(x) x))
})

# use functions that are not exported
createOME = IFC:::createOME
editMetadata = IFC:::editMetadata
formatdate = IFC:::formatdate

# create OME template, this avoid to repeat creation of almost same xml for each file
ome_template = createOME(c(1,1,length(param$chan_to_keep)), param, name = basename(rif_file), date = "YYYY:MM:DDTHH:MM:SSZ")
nam_node = xml2::xml_find_first(ome_template, xpath = "Image")
pix_node = xml2::xml_find_first(ome_template, xpath = "Image/Pixels")
dat_node = xml2::xml_find_first(ome_template, xpath = "Image/AcquisitionDate")

# add OME metadata to exported_file_list files
modified_file_list = sapply(exported_file_list, FUN = function(f) {
  IFD = IFC::getIFD(f, trunc_bytes = 20)
  xml2::xml_set_attr(nam_node, attr = "Name", value = basename(f))
  xml2::xml_set_text(dat_node, formatdate(IFD[[1]]$tags$`306`$map, iso = TRUE))
  xml2::xml_set_attr(pix_node, attr = "SizeX", value = IFD[[1]]$infos$IMAGE_WIDTH)
  xml2::xml_set_attr(pix_node, attr = "SizeY", value = IFD[[1]]$infos$IMAGE_LENGTH)
  xml2::xml_set_attr(pix_node, attr = "SizeC", value = length(param$chan_to_keep))
  editMetadata(f, metadata = as.character(ome_template))
})

# will print ome-xml in tag 270
lapply(exported_file_list, FUN = function(f) {
  IFD = IFC::getIFD(f)
  print(sapply(IFD[[1]]$tags, FUN = function(x) x))
  cat(IFC::getFullTag(IFD, 1, "270"))
})
```

If you are OK, I think we can close this issue (I already check the tasks as completed)

**Comment by rmassei** [comment]
Hi @gitdemont,
thanks a lot for this, this was of great help and, I hope, it helped also for the development of the IFC package.
I will keep you updated on my experience with the 0.2.1.611, ome.xml and multichannel tiff files!

**Comment by gitdemont** [comment]
;) Yes please tell back
